import type { Metadata } from "next";
import localFont from "next/font/local";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import { MemoProvider } from "./contexts/MemoContext";
import { MockDataProvider } from "@/contexts/mockDataContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProvider>
          <MemoProvider>
            <MockDataProvider>
            {children}
            </MockDataProvider>
          </MemoProvider>
        </SessionProvider>
      </body>
    </html>
  );
}


// TODO セッションの管理・整合性の担保をクライアント/サーバのいずれで行うかそしてタイミング等に関してもより厳密に設計
// src/components/AuthProvider.tsx
// "use client";

// import { SessionProvider } from "next-auth/react";
// import { ReactNode } from "react";

// interface AuthProviderProps {
//   children: ReactNode;
// }

// export function AuthProvider({ children }: AuthProviderProps) {
//   return <SessionProvider>{children}</SessionProvider>;
// }
